//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/GameInputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputSystem_Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputSystem_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Build Mode"",
            ""id"": ""862c4012-a464-4573-930a-319d8e7feee6"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""1a3f76f9-bcf7-47b9-9b05-7b83888c1f7a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""18a22a11-3c06-47b2-a065-ba7317a005dc"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f0ff555-4f75-4105-bee9-6cf5b9c6bb06"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Play Mode"",
            ""id"": ""2f8d07ca-a687-45d3-b140-aca20a01c53d"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""cf5bf24d-e481-43fc-9478-e83176a3a379"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b38dad8a-c8ae-4faf-927d-d06e91793751"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Global Mode"",
            ""id"": ""2b48ae2b-f59b-45a2-b16f-176feeaf0f7d"",
            ""actions"": [
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""5c660ba7-0a8a-4fdf-9feb-6aad80d7c3a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PauseEnter"",
                    ""type"": ""Button"",
                    ""id"": ""bff1733d-d5ae-43b2-a6e7-79dcf42b076c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseExit"",
                    ""type"": ""Button"",
                    ""id"": ""38d934f3-9072-4d04-a26e-5e90f222d56b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildEnter"",
                    ""type"": ""Button"",
                    ""id"": ""baaad142-850b-4fd1-ad61-3dd2d7f93c68"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildExit"",
                    ""type"": ""Button"",
                    ""id"": ""4af984fe-5e5a-47e8-8901-71858efc7765"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameEnter"",
                    ""type"": ""Button"",
                    ""id"": ""a3bf2e91-87c0-4190-81df-896d108304ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameExit"",
                    ""type"": ""Button"",
                    ""id"": ""6b114e1d-64dc-44ba-8b8b-d4d8b93a94ec"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24d99444-33e0-4c98-b7b8-60ebae3efeb2"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee5bf243-b91f-4352-8085-e8390eedc651"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4fc961a-0d4d-4167-8cc2-3c06514ce126"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseEnter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac802f0f-0d70-4564-a9c3-cf94356da2c7"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80927585-6a42-48e6-a8f7-0a0f3710681f"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameEnter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f39fd96-3a05-425e-a914-2dbf3c8a1812"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77383355-9bf9-4a26-a145-739a9933bd26"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildEnter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ba945db-43c0-4108-b0ee-bf888a788917"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildExit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Build Mode
        m_BuildMode = asset.FindActionMap("Build Mode", throwIfNotFound: true);
        m_BuildMode_Click = m_BuildMode.FindAction("Click", throwIfNotFound: true);
        // Play Mode
        m_PlayMode = asset.FindActionMap("Play Mode", throwIfNotFound: true);
        m_PlayMode_Click = m_PlayMode.FindAction("Click", throwIfNotFound: true);
        // Global Mode
        m_GlobalMode = asset.FindActionMap("Global Mode", throwIfNotFound: true);
        m_GlobalMode_PointerPosition = m_GlobalMode.FindAction("PointerPosition", throwIfNotFound: true);
        m_GlobalMode_PauseEnter = m_GlobalMode.FindAction("PauseEnter", throwIfNotFound: true);
        m_GlobalMode_PauseExit = m_GlobalMode.FindAction("PauseExit", throwIfNotFound: true);
        m_GlobalMode_BuildEnter = m_GlobalMode.FindAction("BuildEnter", throwIfNotFound: true);
        m_GlobalMode_BuildExit = m_GlobalMode.FindAction("BuildExit", throwIfNotFound: true);
        m_GlobalMode_GameEnter = m_GlobalMode.FindAction("GameEnter", throwIfNotFound: true);
        m_GlobalMode_GameExit = m_GlobalMode.FindAction("GameExit", throwIfNotFound: true);
    }

    ~@GameInputSystem_Actions()
    {
        UnityEngine.Debug.Assert(!m_BuildMode.enabled, "This will cause a leak and performance issues, GameInputSystem_Actions.BuildMode.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayMode.enabled, "This will cause a leak and performance issues, GameInputSystem_Actions.PlayMode.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_GlobalMode.enabled, "This will cause a leak and performance issues, GameInputSystem_Actions.GlobalMode.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Build Mode
    private readonly InputActionMap m_BuildMode;
    private List<IBuildModeActions> m_BuildModeActionsCallbackInterfaces = new List<IBuildModeActions>();
    private readonly InputAction m_BuildMode_Click;
    public struct BuildModeActions
    {
        private @GameInputSystem_Actions m_Wrapper;
        public BuildModeActions(@GameInputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_BuildMode_Click;
        public InputActionMap Get() { return m_Wrapper.m_BuildMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildModeActions set) { return set.Get(); }
        public void AddCallbacks(IBuildModeActions instance)
        {
            if (instance == null || m_Wrapper.m_BuildModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuildModeActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IBuildModeActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IBuildModeActions instance)
        {
            if (m_Wrapper.m_BuildModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuildModeActions instance)
        {
            foreach (var item in m_Wrapper.m_BuildModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuildModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuildModeActions @BuildMode => new BuildModeActions(this);

    // Play Mode
    private readonly InputActionMap m_PlayMode;
    private List<IPlayModeActions> m_PlayModeActionsCallbackInterfaces = new List<IPlayModeActions>();
    private readonly InputAction m_PlayMode_Click;
    public struct PlayModeActions
    {
        private @GameInputSystem_Actions m_Wrapper;
        public PlayModeActions(@GameInputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_PlayMode_Click;
        public InputActionMap Get() { return m_Wrapper.m_PlayMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayModeActions set) { return set.Get(); }
        public void AddCallbacks(IPlayModeActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayModeActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IPlayModeActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IPlayModeActions instance)
        {
            if (m_Wrapper.m_PlayModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayModeActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayModeActions @PlayMode => new PlayModeActions(this);

    // Global Mode
    private readonly InputActionMap m_GlobalMode;
    private List<IGlobalModeActions> m_GlobalModeActionsCallbackInterfaces = new List<IGlobalModeActions>();
    private readonly InputAction m_GlobalMode_PointerPosition;
    private readonly InputAction m_GlobalMode_PauseEnter;
    private readonly InputAction m_GlobalMode_PauseExit;
    private readonly InputAction m_GlobalMode_BuildEnter;
    private readonly InputAction m_GlobalMode_BuildExit;
    private readonly InputAction m_GlobalMode_GameEnter;
    private readonly InputAction m_GlobalMode_GameExit;
    public struct GlobalModeActions
    {
        private @GameInputSystem_Actions m_Wrapper;
        public GlobalModeActions(@GameInputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PointerPosition => m_Wrapper.m_GlobalMode_PointerPosition;
        public InputAction @PauseEnter => m_Wrapper.m_GlobalMode_PauseEnter;
        public InputAction @PauseExit => m_Wrapper.m_GlobalMode_PauseExit;
        public InputAction @BuildEnter => m_Wrapper.m_GlobalMode_BuildEnter;
        public InputAction @BuildExit => m_Wrapper.m_GlobalMode_BuildExit;
        public InputAction @GameEnter => m_Wrapper.m_GlobalMode_GameEnter;
        public InputAction @GameExit => m_Wrapper.m_GlobalMode_GameExit;
        public InputActionMap Get() { return m_Wrapper.m_GlobalMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GlobalModeActions set) { return set.Get(); }
        public void AddCallbacks(IGlobalModeActions instance)
        {
            if (instance == null || m_Wrapper.m_GlobalModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GlobalModeActionsCallbackInterfaces.Add(instance);
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
            @PauseEnter.started += instance.OnPauseEnter;
            @PauseEnter.performed += instance.OnPauseEnter;
            @PauseEnter.canceled += instance.OnPauseEnter;
            @PauseExit.started += instance.OnPauseExit;
            @PauseExit.performed += instance.OnPauseExit;
            @PauseExit.canceled += instance.OnPauseExit;
            @BuildEnter.started += instance.OnBuildEnter;
            @BuildEnter.performed += instance.OnBuildEnter;
            @BuildEnter.canceled += instance.OnBuildEnter;
            @BuildExit.started += instance.OnBuildExit;
            @BuildExit.performed += instance.OnBuildExit;
            @BuildExit.canceled += instance.OnBuildExit;
            @GameEnter.started += instance.OnGameEnter;
            @GameEnter.performed += instance.OnGameEnter;
            @GameEnter.canceled += instance.OnGameEnter;
            @GameExit.started += instance.OnGameExit;
            @GameExit.performed += instance.OnGameExit;
            @GameExit.canceled += instance.OnGameExit;
        }

        private void UnregisterCallbacks(IGlobalModeActions instance)
        {
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
            @PauseEnter.started -= instance.OnPauseEnter;
            @PauseEnter.performed -= instance.OnPauseEnter;
            @PauseEnter.canceled -= instance.OnPauseEnter;
            @PauseExit.started -= instance.OnPauseExit;
            @PauseExit.performed -= instance.OnPauseExit;
            @PauseExit.canceled -= instance.OnPauseExit;
            @BuildEnter.started -= instance.OnBuildEnter;
            @BuildEnter.performed -= instance.OnBuildEnter;
            @BuildEnter.canceled -= instance.OnBuildEnter;
            @BuildExit.started -= instance.OnBuildExit;
            @BuildExit.performed -= instance.OnBuildExit;
            @BuildExit.canceled -= instance.OnBuildExit;
            @GameEnter.started -= instance.OnGameEnter;
            @GameEnter.performed -= instance.OnGameEnter;
            @GameEnter.canceled -= instance.OnGameEnter;
            @GameExit.started -= instance.OnGameExit;
            @GameExit.performed -= instance.OnGameExit;
            @GameExit.canceled -= instance.OnGameExit;
        }

        public void RemoveCallbacks(IGlobalModeActions instance)
        {
            if (m_Wrapper.m_GlobalModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGlobalModeActions instance)
        {
            foreach (var item in m_Wrapper.m_GlobalModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GlobalModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GlobalModeActions @GlobalMode => new GlobalModeActions(this);
    public interface IBuildModeActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
    public interface IPlayModeActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
    public interface IGlobalModeActions
    {
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnPauseEnter(InputAction.CallbackContext context);
        void OnPauseExit(InputAction.CallbackContext context);
        void OnBuildEnter(InputAction.CallbackContext context);
        void OnBuildExit(InputAction.CallbackContext context);
        void OnGameEnter(InputAction.CallbackContext context);
        void OnGameExit(InputAction.CallbackContext context);
    }
}
